export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGOUT = 'LOGOUT'

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'


export const PARKING_SPACES_GET_ALL_REQUEST = 'PARKING_SPACES_GET_ALL_REQUEST'
export const PARKING_SPACES_GET_ALL_SUCCESS = 'PARKING_SPACES_GET_ALL_SUCCESS'
export const PARKING_SPACES_GET_ALL_FAILURE = 'PARKING_SPACES_GET_ALL_FAIL'
export const PARKING_SPACES_CREATE_REQUEST = 'PARKING_SPACES_CREATE_REQUEST'
export const PARKING_SPACES_CREATE_SUCCESS = 'PARKING_SPACES_CREATE_SUCCESS'
export const PARKING_SPACES_CREATE_FAILURE = 'PARKING_SPACES_CREATE_FAIL'
export const PARKING_SPACES_DELETE_REQUEST = 'PARKING_SPACES_DELETE_REQUEST'
export const PARKING_SPACES_DELETE_SUCCESS = 'PARKING_SPACES_DELETE_SUCCESS'
export const PARKING_SPACES_DELETE_FAILURE = 'PARKING_SPACES_DELETE_FAIL'
export const PARKING_SPACES_GET_ONE_REQUEST = 'PARKING_SPACES_GET_ONE_REQUEST'
export const PARKING_SPACES_GET_ONE_SUCCESS = 'PARKING_SPACES_GET_ONE_SUCCESS'
export const PARKING_SPACES_GET_ONE_FAILURE = 'PARKING_SPACES_GET_ONE_FAIL'

export const PARKING_SPACES_ASSIGN_REQUEST = 'PARKING_SPACES_ASSIGN_REQUEST'
export const PARKING_SPACES_ASSIGN_SUCCESS = 'PARKING_SPACES_ASSIGN_SUCCESS'
export const PARKING_SPACES_ASSIGN_FAILURE = 'PARKING_SPACES_ASSIGN_FAILURE'


export const USERS_GET_ALL_REQUEST = 'USERS_GET_ALL_REQUEST'
export const USERS_GET_ALL_SUCCESS = 'USERS_GET_ALL_SUCCESS'
export const USERS_GET_ALL_FAILURE = 'USERS_GET_ALL_FAIL'
export const USERS_DELETE_ONE_REQUEST = 'USERS_DELETE_ONE_REQUEST'
export const USERS_DELETE_ONE_SUCCESS = 'USERS_DELETE_ONE_SUCCESS'
export const USERS_DELETE_ONE_FAILURE = 'USERS_DELETE_ONE_FAIL'
export const USERS_GET_ONE_REQUEST = 'USERS_GET_ONE_REQUEST'
export const USERS_GET_ONE_SUCCESS = 'USERS_GET_ONE_SUCCESS'
export const USERS_GET_ONE_FAILURE = 'USERS_GET_ONE_FAIL'
export const USERS_UPDATE_ONE_REQUEST = 'USERS_UPDATE_ONE_REQUEST'
export const USERS_UPDATE_ONE_SUCCESS = 'USERS_UPDATE_ONE_SUCCESS'
export const USERS_UPDATE_ONE_FAILURE = 'USERS_UPDATE_ONE_FAIL'


