export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGOUT = 'LOGOUT'

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'


export const PARKING_SPACES_GET_ALL_REQUEST = 'PARKING_SPACES_GET_ALL_REQUEST'
export const PARKING_SPACES_GET_ALL_SUCCESS = 'PARKING_SPACES_GET_ALL_SUCCESS'
export const PARKING_SPACES_GET_ALL_FAILURE = 'PARKING_SPACES_GET_ALL_FAIL'

export const PARKING_SPACES_ASSIGN_REQUEST = 'PARKING_SPACES_ASSIGN_REQUEST'
export const PARKING_SPACES_ASSIGN_SUCCESS = 'PARKING_SPACES_ASSIGN_SUCCESS'
export const PARKING_SPACES_ASSIGN_FAILURE = 'PARKING_SPACES_ASSIGN_FAILURE'